apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:  prod-cluster
  region: ap-south-1
  version: "1.33"

vpc:
  id: "vpc-083ecb697ff15"
  subnets:
    private:
      ap-south-1a:
          id: "subnet-096bb373601a"
      ap-south-1b:
          id: "subnet-04885a92"
      ap-south-1c:
          id: "subnet-00917fe4b62d"

    public:
      public-ap-south-1a:
          id: "subnet-0d6635a6a"
      public-ap-south-1b:
          id: "subnet-0e278fd45"
      public-ap-south-1c:
          id: "subnet-04d343b8f9"
addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
    configurationValues: |
      {
        "defaultStorageClass": {
          "enabled": true
        }
      }

managedNodeGroups:
  - name: prod-nodes
    privateNetworking: true
    availabilityZones:
      - ap-south-1a
      - ap-south-1b
      - ap-south-1c
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
    instanceType: "c6a.xlarge"
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        awsLoadBalancerController: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
    ssh:
      enableSsm: true
    volumeSize: 60
    volumeType: gp3

